modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Rebel459/farmers-knives/issues"
license = "LGPL-3.0 Only"

[[mods]]
modId = "farmersknives"
version = "${version}"
displayName = "Farmer's Knives"
authors = "Rebel459"
description = '''
Adds Knives to Farmer's Delight for many other mods
'''
#logoFile = ""

[[dependencies.farmersknives]]
modId = "neoforge"
type = "required"
versionRange = "[1.21,1.21.1)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farmersknives]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farmersknives]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "farmersknives.mixins.json"
